<a href="https://colab.research.google.com/github/EstebanPerez25/Proyecto-Final-IDM/blob/main/Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Wrangling

**Conversion of csv to parquet file**

In [73]:
# import pandas as pd

raw_df = pd.read_csv('reservaciones.csv')
raw_df.to_parquet('reservaciones.parquet')

### Libraries

In [ ]:
!pip install ydata_profiling

In [118]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data profiling
from ydata_profiling import ProfileReport
from ydata_profiling.utils.cache import cache_file

### Load data

In [76]:
raw_df = pd.read_parquet('reservaciones.parquet')
raw_df.head()

,id_reservaciones,fecha_hoy,fecha_reservacion,fecha_llegada,fecha_salida,numero_personas,numero_personas_anio_anterior,numero_adultos,numero_adultos_anio_anterior,numero_menores,...,nombre_estatus_reservacion,clave_estado,nombre_estado,total_tarifa,id_moneda,fecha_ultimo_cambio,reservacion,reservacion_anio_anterior,id_cliente_disp,cliente_disp_anio_anterior
0,0,16/08/2019,16/08/2019,07/11/2019,10/11/2019,2,0,2,0,0,...,SALIDA,EMX,MÉXICO,2659.98,1,10/11/2019,1,0,2,0
1,1,22/10/2019,22/10/2019,01/12/2019,05/12/2019,4,0,4,0,0,...,SALIDA,EGT,GUANAJUATO,1764.00,1,05/12/2019,1,0,4,0
2,2,28/10/2019,28/10/2019,01/12/2019,05/12/2019,2,0,2,0,0,...,SALIDA,EMC,MICHOACÁN,2660.04,1,05/12/2019,1,0,2,0
3,3,28/10/2019,28/10/2019,08/12/2019,11/12/2019,4,0,3,0,0,...,SALIDA,EGT,GUANAJUATO,1995.03,1,11/12/2019,1,0,3,0
4,4,28/10/2019,28/10/2019,08/12/2019,12/12/2019,2,0,2,0,0,...,SALIDA,EMX,MÉXICO,13369.92,1,12/12/2019,1,0,2,0

In [77]:
raw_df.shape

(203002, 49)

## Basic data preprocessing

In [78]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203002 entries, 0 to 203001
Data columns (total 49 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id_reservaciones                  203002 non-null  int64
 1   fecha_hoy                         203002 non-null  object
 2   fecha_reservacion                 203002 non-null  object
 3   fecha_llegada                     203000 non-null  object
 4   fecha_salida                      202968 non-null  object
 5   numero_personas                   203002 non-null  int64
 6   numero_personas_anio_anterior     203002 non-null  int64
 7   numero_adultos                    203002 non-null  int64
 8   numero_adultos_anio_anterior      203002 non-null  int64
 9   numero_menores                    203002 non-null  int64
 10  numero_menores_anio_anterior      203002 non-null  int64
 11  numero_noches                     203002 non-null  int64
 12  numero_noches_anio_anterior       203002 non-null  int64
 13  total_habitaciones                203002 non-null  int64
 14  total_habitaciones_anio_anterior  203002 non-null  int64
 15  id_programa                       203002 non-null  int64
 16  nombre_programa                   203002 non-null  object
 17  id_paquete                        203002 non-null  int64
 18  nombre_paquete                    203002 non-null  object
 19  id_segmento                       203002 non-null  int64
 20  nombre_segmento                   203002 non-null  object
 21  id_agencia                        203002 non-null  int64
 22  nombre_agencia                    203002 non-null  object
 23  ciudad_agencia                    203002 non-null  object
 24  entidad_federativa_agencia        203002 non-null  object
 25  pais_agencia                      203002 non-null  object
 26  id_empresa                        203002 non-null  int64
 27  nombre_empresa                    203002 non-null  object
 28  total_habitaciones_empresa        203002 non-null  int64
 29  id_tipo_habitacion                203002 non-null  int64
 30  nombre_tipo_habitacion            203002 non-null  object
 31  cupo_tipo_habitacion              202992 non-null  float64
 32  clasificacion_tipo_habitacion     202992 non-null  object
 33  id_canal                          203002 non-null  int64
 34  nombre_canal                      203002 non-null  object
 35  id_pais_origen                    203002 non-null  int64
 36  nombre_pais_origen                203002 non-null  object
 37  reservacion_pendiente             203002 non-null  int64
 38  id_estatus_reservacion            203002 non-null  int64
 39  nombre_estatus_reservacion        203002 non-null  object
 40  clave_estado                      203002 non-null  object
 41  nombre_estado                     203000 non-null  object
 42  total_tarifa                      203002 non-null  float64
 43  id_moneda                         203002 non-null  int64
 44  fecha_ultimo_cambio               202505 non-null  object
 45  reservacion                       203002 non-null  int64
 46  reservacion_anio_anterior         203002 non-null  int64
 47  id_cliente_disp                   203002 non-null  int64
 48  cliente_disp_anio_anterior        203002 non-null  int64
dtypes: float64(2), int64(27), object(20)
memory usage: 75.9+ MB

### Correct datatypes

In [107]:
datatypes_df = raw_df.copy()

# Columns to datetime type
date_columns = ['fecha_hoy', 'fecha_reservacion',
                'fecha_llegada', 'fecha_salida',
                'fecha_ultimo_cambio']
# Columns to category type
categorical_columns = [
    # IDs
    'id_programa',
    'id_paquete',
    'id_segmento',
    'id_agencia',
    'id_empresa',
    'id_tipo_habitacion',
    'id_canal',
    'id_pais_origen',
    'id_estatus_reservacion',
    'id_moneda',
    'id_cliente_disp',

    # Variables nominales/texto
    'nombre_programa',
    'nombre_paquete',
    'nombre_segmento',
    'nombre_agencia',
    'ciudad_agencia',
    'entidad_federativa_agencia',
    'pais_agencia',
    'nombre_empresa',
    'nombre_tipo_habitacion',
    'clasificacion_tipo_habitacion',
    'nombre_canal',
    'nombre_pais_origen',
    'nombre_estatus_reservacion',
    'clave_estado',
    'nombre_estado'
]

# Columns to binary type
bool_columns = ['reservacion_pendiente',
                'reservacion',
                'reservacion_anio_anterior']


# for column in date_columns:
#   datatypes_df[column] = pd.to_datetime(raw_df[column],
#                                         errors='coerce',
#                                         dayfirst=True )

datatypes_df[date_columns] = raw_df[date_columns].astype('datetime64[ns]')
datatypes_df[categorical_columns] = raw_df[categorical_columns].astype('category')
datatypes_df[bool_columns] = raw_df[bool_columns].astype('bool')

datatypes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203002 entries, 0 to 203001
Data columns (total 49 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id_reservaciones                  203002 non-null  int64
 1   fecha_hoy                         203002 non-null  datetime64[ns]
 2   fecha_reservacion                 203002 non-null  datetime64[ns]
 3   fecha_llegada                     203000 non-null  datetime64[ns]
 4   fecha_salida                      202968 non-null  datetime64[ns]
 5   numero_personas                   203002 non-null  int64
 6   numero_personas_anio_anterior     203002 non-null  int64
 7   numero_adultos                    203002 non-null  int64
 8   numero_adultos_anio_anterior      203002 non-null  int64
 9   numero_menores                    203002 non-null  int64
 10  numero_menores_anio_anterior      203002 non-null  int64
 11  numero_noches                     203002 non-null  int64
 12  numero_noches_anio_anterior       203002 non-null  int64
 13  total_habitaciones                203002 non-null  int64
 14  total_habitaciones_anio_anterior  203002 non-null  int64
 15  id_programa                       203002 non-null  category
 16  nombre_programa                   203002 non-null  category
 17  id_paquete                        203002 non-null  category
 18  nombre_paquete                    203002 non-null  category
 19  id_segmento                       203002 non-null  category
 20  nombre_segmento                   203002 non-null  category
 21  id_agencia                        203002 non-null  category
 22  nombre_agencia                    203002 non-null  category
 23  ciudad_agencia                    203002 non-null  category
 24  entidad_federativa_agencia        203002 non-null  category
 25  pais_agencia                      203002 non-null  category
 26  id_empresa                        203002 non-null  category
 27  nombre_empresa                    203002 non-null  category
 28  total_habitaciones_empresa        203002 non-null  int64
 29  id_tipo_habitacion                203002 non-null  category
 30  nombre_tipo_habitacion            203002 non-null  category
 31  cupo_tipo_habitacion              202992 non-null  float64
 32  clasificacion_tipo_habitacion     202992 non-null  category
 33  id_canal                          203002 non-null  category
 34  nombre_canal                      203002 non-null  category
 35  id_pais_origen                    203002 non-null  category
 36  nombre_pais_origen                203002 non-null  category
 37  reservacion_pendiente             203002 non-null  bool
 38  id_estatus_reservacion            203002 non-null  category
 39  nombre_estatus_reservacion        203002 non-null  category
 40  clave_estado                      203002 non-null  category
 41  nombre_estado                     203000 non-null  category
 42  total_tarifa                      203002 non-null  float64
 43  id_moneda                         203002 non-null  category
 44  fecha_ultimo_cambio               202505 non-null  datetime64[ns]
 45  reservacion                       203002 non-null  bool
 46  reservacion_anio_anterior         203002 non-null  bool
 47  id_cliente_disp                   203002 non-null  category
 48  cliente_disp_anio_anterior        203002 non-null  int64
dtypes: bool(3), category(26), datetime64[ns](5), float64(2), int64(13)
memory usage: 37.0 MB

**Capitalize string columns**

In [108]:
capitalized_df = datatypes_df.copy()

def capitalize_words(text):
  if isinstance(text, str):
    words = text.split()
    capitalized_words = [word.capitalize() for word in words]
    return " ".join(capitalized_words)
  return text

# Apply the function to string columns
for col in datatypes_df.select_dtypes(include='category').columns:
  capitalized_df[col] = datatypes_df[col].apply(capitalize_words)

# Visualize capitalized columns
capitalized_df[capitalized_df.select_dtypes(include='category').columns].head()

,id_programa,nombre_programa,id_paquete,nombre_paquete,id_segmento,nombre_segmento,id_agencia,nombre_agencia,ciudad_agencia,entidad_federativa_agencia,...,id_canal,nombre_canal,id_pais_origen,nombre_pais_origen,id_estatus_reservacion,nombre_estatus_reservacion,clave_estado,nombre_estado,id_moneda,id_cliente_disp
0,1,Ninguno,1,Walk In,14,Individual Ep/vac. Club,112,Hoteles S.a.,Mexico City,México,...,10,Multivacaciones 2,157,Mexico,9,Salida,Emx,México,1,2
1,1,Ninguno,2,Ninguno,14,Individual Ep/vac. Club,112,Hoteles S.a.,Mexico City,México,...,10,Multivacaciones 2,157,Mexico,9,Salida,Egt,Guanajuato,1,4
2,1,Ninguno,1,Walk In,14,Individual Ep/vac. Club,112,Hoteles S.a.,Mexico City,México,...,10,Multivacaciones 2,157,Mexico,9,Salida,Emc,Michoacán,1,2
3,1,Ninguno,2,Ninguno,14,Individual Ep/vac. Club,112,Hoteles S.a.,Mexico City,México,...,10,Multivacaciones 2,157,Mexico,9,Salida,Egt,Guanajuato,1,3
4,1,Ninguno,1,Walk In,5,Ecommerce Ota Domestic,14,Bestday Travel Group,Cancún,Quintana Roo,...,13,Vertical Booking,157,Mexico,9,Salida,Emx,México,1,2

**Null values**

In [109]:
capitalized_df.isna().sum()

id_reservaciones                      0
fecha_hoy                             0
fecha_reservacion                     0
fecha_llegada                         2
fecha_salida                         34
numero_personas                       0
numero_personas_anio_anterior         0
numero_adultos                        0
numero_adultos_anio_anterior          0
numero_menores                        0
numero_menores_anio_anterior          0
numero_noches                         0
numero_noches_anio_anterior           0
total_habitaciones                    0
total_habitaciones_anio_anterior      0
id_programa                           0
nombre_programa                       0
id_paquete                            0
nombre_paquete                        0
id_segmento                           0
nombre_segmento                       0
id_agencia                            0
nombre_agencia                        0
ciudad_agencia                        0
entidad_federativa_agencia            0
pais_agencia                          0
id_empresa                            0
nombre_empresa                        0
total_habitaciones_empresa            0
id_tipo_habitacion                    0
nombre_tipo_habitacion                0
cupo_tipo_habitacion                 10
clasificacion_tipo_habitacion        10
id_canal                              0
nombre_canal                          0
id_pais_origen                        0
nombre_pais_origen                    0
reservacion_pendiente                 0
id_estatus_reservacion                0
nombre_estatus_reservacion            0
clave_estado                          0
nombre_estado                         2
total_tarifa                          0
id_moneda                             0
fecha_ultimo_cambio                 497
reservacion                           0
reservacion_anio_anterior             0
id_cliente_disp                       0
cliente_disp_anio_anterior            0
dtype: int64

**Duplicated values**

In [110]:
capitalized_df.duplicated().sum()

np.int64(0)

Removing unique id to verify duplicates in other columns.

In [111]:
capitalized_df.drop('id_reservaciones', axis=1).duplicated().sum()

np.int64(75606)

In [112]:
capitalized_df[capitalized_df.drop('id_reservaciones', axis=1).duplicated()].head(8)

,id_reservaciones,fecha_hoy,fecha_reservacion,fecha_llegada,fecha_salida,numero_personas,numero_personas_anio_anterior,numero_adultos,numero_adultos_anio_anterior,numero_menores,...,nombre_estatus_reservacion,clave_estado,nombre_estado,total_tarifa,id_moneda,fecha_ultimo_cambio,reservacion,reservacion_anio_anterior,id_cliente_disp,cliente_disp_anio_anterior
17,17,2019-08-17,2019-08-17,2019-07-11,2019-10-11,2,0,2,0,0,...,Reservacion Cancelada,Egr,Guerrero,8088.0,1,2019-06-11,True,False,2,0
19,19,2019-08-17,2019-08-17,2019-07-11,2019-10-11,2,0,2,0,0,...,Reservacion Cancelada,Egr,Guerrero,8088.0,1,2019-06-11,True,False,2,0
20,20,2019-08-17,2019-08-17,2019-07-11,2019-10-11,2,0,2,0,0,...,Reservacion Cancelada,Egr,Guerrero,8088.0,1,2019-06-11,True,False,2,0
22,22,2019-08-17,2019-08-17,2019-08-11,2019-10-11,2,0,2,0,0,...,Salida,Emc,Michoacán,5392.0,1,2019-10-11,True,False,2,0
25,25,2019-08-17,2019-08-17,2019-08-11,2019-10-11,2,0,2,0,0,...,Salida,Emc,Michoacán,5392.0,1,2019-10-11,True,False,2,0
26,26,2019-08-17,2019-08-17,2019-08-11,2019-10-11,2,0,2,0,0,...,Salida,Emc,Michoacán,5392.0,1,2019-10-11,True,False,2,0
27,27,2019-08-17,2019-08-17,2019-08-11,2019-10-11,2,0,2,0,0,...,Salida,Emc,Michoacán,5392.0,1,2019-10-11,True,False,2,0
28,28,2019-08-17,2019-08-17,2019-08-11,2019-10-11,2,0,2,0,0,...,Salida,Emc,Michoacán,5392.0,1,2019-10-11,True,False,2,0

These records may be matches, not necessarily duplicate values.

## EDA

In [ ]:
df_eda = capitalized_df.copy()

### Data Profiling

In [ ]:
profile_report = ProfileReport(df_eda, title="Reservaciones Profiling Report")

In [ ]:
#profile_report.to_notebook_iframe()

In [ ]:
profile_report.to_file("Reservaciones_Profile_Report.html")

## EDA - Univariate

### Descriptive stats

In [114]:
df_eda.describe()

,id_reservaciones,fecha_hoy,fecha_reservacion,fecha_llegada,fecha_salida,numero_personas,numero_personas_anio_anterior,numero_adultos,numero_adultos_anio_anterior,numero_menores,numero_menores_anio_anterior,numero_noches,numero_noches_anio_anterior,total_habitaciones,total_habitaciones_anio_anterior,total_habitaciones_empresa,cupo_tipo_habitacion,total_tarifa,fecha_ultimo_cambio,cliente_disp_anio_anterior
count,203002.00000,203002,203002,203000,202968,203002.000000,203002.000000,203002.000000,203002.000000,203002.000000,203002.000000,203002.000000,203002.000000,203002.000000,203002.000000,203002.0,202992.0,2.030020e+05,202505,203002.000000
mean,101500.50000,2020-02-26 00:45:45.620239872,2019-08-28 09:57:46.712643072,2019-11-01 22:33:56.855172352,2019-11-08 17:20:49.804895232,1.185865,1.170550,1.094708,1.079694,0.034108,0.033734,1.680028,1.656043,0.505581,0.498586,735.0,2.0,4.106728e+03,2019-10-08 05:21:16.324041728,1.079694
min,0.00000,2019-01-02 00:00:00,2019-01-02 00:00:00,2019-01-03 00:00:00,2019-01-03 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,735.0,2.0,-3.091000e+04,2019-01-02 00:00:00,0.000000
25%,50750.25000,2019-08-03 00:00:00,2019-04-16 00:00:00,2019-06-07 00:00:00,2019-06-13 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,735.0,2.0,0.000000e+00,2019-06-04 00:00:00,0.000000
50%,101500.50000,2020-02-25 00:00:00,2019-08-03 00:00:00,2019-10-05 00:00:00,2019-10-13 00:00:00,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,735.0,2.0,0.000000e+00,2019-09-30 00:00:00,0.000000
75%,152250.75000,2020-08-16 00:00:00,2019-12-27 00:00:00,2020-03-09 00:00:00,2020-03-16 00:00:00,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,3.000000,3.000000,1.000000,1.000000,735.0,2.0,7.592000e+03,2020-01-30 00:00:00,2.000000
max,203001.00000,2021-12-03 00:00:00,2020-12-04 00:00:00,2021-12-06 00:00:00,2021-12-06 00:00:00,32.000000,32.000000,15.000000,15.000000,15.000000,15.000000,687.000000,687.000000,6.000000,6.000000,735.0,2.0,1.033056e+06,2020-12-07 00:00:00,15.000000
std,58601.77401,NaN,NaN,NaN,NaN,1.369629,1.368073,1.207076,1.204694,0.265187,0.264043,2.866189,2.847958,0.508751,0.508489,0.0,0.0,6.501707e+03,NaN,1.204694